#!/bin/bash
echo ""
echo "========================================="
echo "  NANOBOT - Guia Rapido"
echo "========================================="
echo ""
echo "  PRIMEIRO PASSO (sempre):"
echo "    source start.sh"
echo ""
echo "  COMANDOS:"
echo "    nanobot status                Ver configuracao"
echo "    nanobot gateway               Iniciar (foreground, Ctrl+C para)"
echo "    nanobot agent -m \"Ola\"        Mandar mensagem direto"
echo "    nanobot channels status       Ver canais"
echo "    nanobot cron list             Ver tarefas agendadas"
echo "    nanobot security-check        Checar seguranca"
echo ""
echo "  RODAR EM BACKGROUND:"
echo "    nohup python -m nanobot gateway > ~/.nanobot/gateway.log 2>&1 &"
echo ""
echo "  VERIFICAR SE ESTA RODANDO:"
echo "    ps aux | grep 'nanobot gateway'"
echo ""
echo "  PARAR:"
echo "    pkill -f 'nanobot gateway'"
echo ""
echo "  VER LOG AO VIVO:"
echo "    tail -f ~/.nanobot/gateway.log"
echo ""
echo "  ATUALIZAR CODIGO:"
echo "    git pull && pip install -e ."
echo ""
echo "  ARQUIVOS IMPORTANTES:"
echo "    ~/.nanobot/config.json        Configuracao (chaves, modelo, canais)"
echo "    ~/.nanobot/gateway.log        Log do servidor"
echo "    ~/.nanobot/sessions/          Historico de conversas"
echo "    ~/.nanobot/workspace/         Personalidade do agente"
echo ""
echo "  ATALHOS (aliases no .bashrc):"
echo "    nb                            Ativa o venv"
echo "    nbhelp                        Mostra este guia"
echo ""
echo "========================================="
echo ""
